function p1 = plotLink(T,linewidth,st)
p1 = plot3([0 T(1,4,1)],...
      [0 T(2,4,1)],...
      [0 T(3,4,1)],...
      'k-','LineWidth',linewidth,'Color',st);
hold on;
for idx = 1 : size(T,3) - 1
    plot3([T(1,4,idx) T(1,4,idx + 1)],...
          [T(2,4,idx) T(2,4,idx + 1)],...
          [T(3,4,idx) T(3,4,idx + 1)],...
          'k-','LineWidth',linewidth,'Color',st);
    hold on;
end

end